### ISSUE TITLE
dep init error for containerd/cgroups/v2 

### ISSUE THREAD

**Issue by y0zg** [containerd/cgroups#157]
Hello, 
I got the error while running `dep init -v -no-examples`, please suggest how to deal with this

OS VERSION="18.04.4 LTS (Bionic Beaver)"

```
dep version
dep:
 version     : devel
 build date  : 
 git hash    : 
 go version  : go1.8.3
 go compiler : gc
 platform    : linux/amd64
```

```
(27)  ✗   github.com/coreos/go-systemd at master has problem subpkg(s):
(27)    	github.com/coreos/go-systemd/v22/dbus is missing; required by github.com/containerd/cgroups@master.
(26)    ← no more versions of github.com/coreos/go-systemd to try; begin backtrack
(25)  ← backtrack: popped 28 pkgs from google.golang.org/protobuf
(24)  ← backtrack: popped 3 pkgs from github.com/golang/protobuf
(23)  ← backtrack: no more versions of golang.org/x/text to try
(22)  ← backtrack: popped 1 pkgs from github.com/golang/protobuf
(21)  ← backtrack: no more versions of github.com/Nvveen/Gotty to try
(20)  ← backtrack: popped 28 pkgs from google.golang.org/protobuf
(19)  ← backtrack: no more versions of github.com/gogo/protobuf to try
(18)  ← backtrack: popped 30 pkgs from google.golang.org/protobuf
(17)  ← backtrack: popped 4 pkgs from github.com/fsouza/go-dockerclient
(16)  ← backtrack: popped 2 pkgs from golang.org/x/sys
(15)  ← backtrack: no more versions of google.golang.org/protobuf to try
(14)  ← backtrack: popped 2 pkgs from github.com/Azure/go-ansiterm
(13)  ← backtrack: no more versions of github.com/fsouza/go-dockerclient to try
(12)  ← backtrack: popped 1 pkgs from golang.org/x/sys
(11)  ← backtrack: no more versions of github.com/Azure/go-ansiterm to try
(10)  ← backtrack: popped 1 pkgs from golang.org/x/sys
(9)	← backtrack: no more versions of golang.org/x/crypto to try
(8)	← backtrack: no more versions of github.com/containerd/cgroups to try
(8)	  ? continue github.com/containerd/cgroups with 2 pkgs; 2 more versions to try
(8)	    try github.com/containerd/cgroups@release/1.0
(8)	✗   package github.com/containerd/cgroups/v2 does not exist within project github.com/containerd/cgroups
(8)	    try github.com/containerd/cgroups@release/1.1
(8)	✗   package github.com/containerd/cgroups/v2 does not exist within project github.com/containerd/cgroups
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/golang/dep/internal/gps.(*solver).findValidVersion(0xc420177600, 0xc421047220, 0xc42046c8e0, 0x2, 0x2, 0x0, 0xc42046c8e0)
	github.com/golang/dep/internal/gps/solver.go:911 +0x519
github.com/golang/dep/internal/gps.(*solver).backtrack(0xc420177600, 0xc420511fe0)
	github.com/golang/dep/internal/gps/solver.go:1049 +0x9de
github.com/golang/dep/internal/gps.(*solver).solve(0xc420177600, 0x0, 0x0, 0xc4201fa990)
	github.com/golang/dep/internal/gps/solver.go:495 +0x787
github.com/golang/dep/internal/gps.(*solver).Solve(0xc420177600, 0x21, 0xb34500, 0xc4201fa030, 0xc420016047)
	github.com/golang/dep/internal/gps/solver.go:440 +0xb1
main.(*initCommand).Run(0xc42015baca, 0xc42005f8b0, 0xc4200101f0, 0x0, 0x0, 0x0, 0x0)
	github.com/golang/dep/cmd/dep/init.go:186 +0x8a1
main.(*Config).Run(0xc420076fc0, 0xc420076fc0)
	github.com/golang/dep/cmd/dep/main.go:160 +0x8e5
main.main()
	github.com/golang/dep/cmd/dep/main.go:45 +0x253
```

**Comment by AkihiroSuda** [comment]
The issue is on dep side and yet Go 1.8 is unsupported.
Please use Go 1.13. (1.14 is too new)

**Comment by y0zg** [comment]
@AkihiroSuda thanks, when you are going to support Go 1.14? Seems this is the root cause
